server:
  host: 0.0.0.0
  port: 8000
  public-url: http://127.0.0.1:8000
  front-end-url: http://127.0.0.1:3000
  cors:
    allowed-origins:
      - "*"
  jwt-secret: 123

# https://pkg.go.dev/github.com/danielgtaylor/huma/v2#OpenAPI
openapi:
  servers:
    - url: http://127.0.0.1:8000
      description: Local server
    - url: https://api.dowhile.uz
      description: Production server

infrastructure:
  postgres:
    host: 127.0.0.1
    port: 5432
    db: db
    user: user
    password: password
  redis:
    host: 127.0.0.1
    port: 6379
    password: password

github:
  community-org-name: dowhile-uz-community

github-auth:
  app-name: dowhile-uz-testing
  app-id: 1
  client-id: a
  client-secret: a
  redirect-complete-path: /v1/github-auth/complete
  redirect-front-end-path: /github-auth/complete
  scopes:
    - repo
    - user
