name: dowhile-uz-back-end

services:
  postgres:
    image: postgres:17.2-alpine
    restart: always
    shm_size: 128mb
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack-server:7.2.0-v14
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"
    volumes:
      - .data/redis:/data
    ports:
      - 127.0.0.1:6379:6379
      - 127.0.0.1:8010:8001

  adminer:
    image: adminer
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "128m"
    ports:
      - 127.0.0.1:8011:8080
